version: 2

sources:
  - name: raw
    schema: gz_raw_data #où se situe la table dans BQ
    description: greenwez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales #Quel est le nom exacte de la table dans BQ
        description: sales of greewneez / we have one row per product_id found in each orders_id
        columns:
          - name: "(orders_id || '-' || pdt_id)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: product
        identifier: raw_gz_product
        description: purchase_price by products_id
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: shipping fees and costs of greewneez / we have one row per orders_id
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: adwords_greenweez
        identifier: raw_gz_adwords #Quel est le nom exacte de la table dans BQ
        description: Adwords campaigns of greewneez / we have one row per campaign_key found in each date_date
        columns:
          - name: "(campaign_key || '-' || date_date)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: bing_greenweez
        identifier: raw_gz_bing #Quel est le nom exacte de la table dans BQ
        description: Bing campaigns of greewneez / we have one row per campaign_key found in each date_date
        columns:
          - name: "(campaign_key || '-' || date_date)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: criteo_greenweez
        identifier: raw_gz_criteo #Quel est le nom exacte de la table dans BQ
        description: Criteo campaigns of greewneez / we have one row per campaign_key found in each date_date
        columns:
          - name: "(campaign_key || '-' || date_date)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: facebook_greenweez
        identifier: raw_gz_facebook #Quel est le nom exacte de la table dans BQ
        description: Facebook campaigns of greewneez / we have one row per campaign_key found in each date_date
        columns:
          - name: "(campaign_key || '-' || date_date)"
            description: primary key of the table
            tests:
              - unique
              - not_null

models:
  - name: finance_days
    description: greenwez final output for finance team // mart
    columns:
      - name: date_date
        description: primary key of the table
        tests:
        - unique
        - not_null
      - name: nb_transactions
        description: Daily number of transactions (i.e. COUNT DISTINCT orders_id)
        tests:
        - not_null
      - name: revenue
        description: Daily revenue (i.e. SUM of the revenues of the day)
        tests:
        - not_null
      - name: average_basket
        description: Daily average basket (i.e. SUM of the revenues of the day / COUNT DISTINCT orders_id)
        tests:
        - not_null
      - name: operational_margin
        description: Daily operational margin (i.e. margin + shipping_fee - log_cost - ship_cost)
        tests:
        - not_null
      - name: purchase_cost
        description: Daily purchase cost (i.e. purchase_price x quantity)
        tests:
        - not_null
      - name: shipping_fee
        description: Daily shipping fee (i.e. SUM of the shipping fees of the day)
        tests:
        - not_null
      - name: log_cost
        description: Daily log costs (i.e. SUM of the logcost of the day)
        tests:
        - not_null
      - name: quantity
        description: Daily products sold (i.e. SUM of the quantities sold each day)
        tests:
        - not_null


