version: 2

sources:
  - name: raw
    schema: gz_raw_data #où se situe la table dans BQ
    description: greenwez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales #Quel est le nom exacte de la table dans BQ
        description: sales of greewneez / we have one row per product_id found in each orders_id
        columns:
          - name: "(orders_id || '-' || pdt_id)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: product
        identifier: raw_gz_product
        description: purchase_price by products_id
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: shipping fees and costs of greewneez / we have one row per orders_id
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
